# Simulation




In [2]:
%matplotlib inline
import numpy as np
import pandas as pd

In [46]:
np.random.choice(4, 100, replace=True, p=[.2, .1, .3, .4])

array([2, 0, 3, 0, 0, 3, 2, 0, 3, 2, 3, 3, 2, 3, 2, 3, 1, 0, 3, 0, 0, 3,
       3, 1, 3, 2, 3, 2, 2, 3, 1, 3, 3, 3, 3, 2, 3, 1, 0, 1, 1, 3, 3, 1,
       3, 1, 3, 1, 1, 3, 2, 3, 2, 2, 2, 3, 0, 3, 2, 1, 3, 2, 1, 3, 3, 3,
       0, 3, 3, 0, 3, 2, 2, 1, 3, 0, 0, 2, 2, 2, 3, 3, 2, 2, 2, 2, 3, 2,
       2, 3, 3, 1, 0, 0, 2, 3, 0, 2, 3, 0])

In [20]:
help(np.random.choice)

Help on built-in function choice:

choice(...) method of numpy.random.mtrand.RandomState instance
    choice(a, size=None, replace=True, p=None)
    
    Generates a random sample from a given 1-D array
    
    .. versionadded:: 1.7.0
    
    .. note::
        New code should use the ``choice`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    a : 1-D array-like or int
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated as if a were np.arange(a)
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    replace : boolean, optional
        Whether the sample is with or without replacement
    p : 1-D array-like, optional
        The probabilities associated with each

1. How likely is it that you roll doubles when rolling two dice?

In [107]:
n_trials = nrows = 10000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], n_trials * n_dice).reshape(nrows, ncols)
rolls


array([[15, 20],
       [ 9, 13],
       [10, 15],
       ...,
       [ 4,  1],
       [16, 20],
       [ 3, 16]])

In [108]:
def doubles():
    print('*** Find rows wih same values in a matrix or 2D Numpy array***')
    # Check rows in which all values are equal
    number_of_doubles = 0
    for i in range(rolls.shape[0]):
        if np.all(rolls[i]==rolls[i][0]):
            number_of_doubles = number_of_doubles + 1
    return number_of_doubles
doubles()

*** Find rows wih same values in a matrix or 2D Numpy array***


530

In [145]:
chance_of_doubles = doubles()/rolls.shape[0]
chance_of_doubles
print(chance_of_doubles * 100, "% chance of rolling doubles")

*** Find rows wih same values in a matrix or 2D Numpy array***
5.3 % chance of rolling doubles


2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [150]:
n_trials = nrows = 100000
n_dice = ncols = 8
flips = np.random.choice([0, 1], n_trials * n_dice).reshape(nrows, ncols)
flips

array([[1, 0, 1, ..., 0, 1, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 1, ..., 0, 1, 1],
       ...,
       [0, 0, 0, ..., 1, 1, 0],
       [1, 1, 1, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 1, 0]])

In [151]:
def exactly_three_heads():
    # Check rows in which there are exactly 3 heads
    three_heads = 0
    for i in range(flips.shape[0]):
        if np.all(np.sum(flips[i]) == 3):
            three_heads = three_heads + 1
    return three_heads

exactly_three_heads()

21663

In [155]:
chance_of_exactly_3_heads = (exactly_three_heads()/flips.shape[0])
chance_of_exactly_3_heads
print(round((chance_of_exactly_3_heads * 100), 2), "% chance of getting exactly 3 heads")

21.66 % chance of getting exactly 3 heads


3.  There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

4.  Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

5. Compare Heights
- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

6. a. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

6. b. What is the probability that we observe an installation issue within the first 150 students that download anaconda?

6. c. How likely is it that 450 students all download anaconda without an issue?

7. a. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

7. b. How likely is it that a food truck will show up sometime this week?

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

# Bonus Exercises

- [Mage Duel](https://gist.github.com/ryanorsinger/2996446f02c1bf30fcb3f8fdb88bd51d)

- [Chuck a Luck](https://gist.github.com/ryanorsinger/eac1d7b7e978f90b8390bdc056312123)