# Simulation




In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

In [2]:
np.random.choice(4, 100, replace=True, p=[.2, .1, .3, .4])

array([2, 1, 3, 3, 1, 3, 2, 1, 2, 1, 3, 3, 2, 3, 2, 3, 3, 3, 3, 2, 3, 3,
       3, 2, 2, 3, 2, 2, 3, 0, 2, 0, 3, 2, 1, 2, 0, 3, 1, 2, 1, 1, 2, 2,
       2, 2, 0, 1, 2, 3, 1, 3, 2, 0, 2, 3, 2, 1, 0, 2, 2, 0, 3, 3, 3, 0,
       1, 3, 3, 2, 3, 3, 2, 2, 2, 0, 2, 3, 2, 2, 0, 1, 2, 3, 3, 3, 2, 2,
       2, 2, 3, 3, 3, 2, 1, 3, 0, 3, 2, 3])

In [3]:
help(np.random.choice)

Help on built-in function choice:

choice(...) method of numpy.random.mtrand.RandomState instance
    choice(a, size=None, replace=True, p=None)
    
    Generates a random sample from a given 1-D array
    
    .. versionadded:: 1.7.0
    
    .. note::
        New code should use the ``choice`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    a : 1-D array-like or int
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated as if a were np.arange(a)
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    replace : boolean, optional
        Whether the sample is with or without replacement
    p : 1-D array-like, optional
        The probabilities associated with each

1. How likely is it that you roll doubles when rolling two dice?

In [4]:
n_trials = nrows = 10000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], n_trials * n_dice).reshape(nrows, ncols)
rolls


array([[ 3,  6],
       [17, 20],
       [16,  6],
       ...,
       [10,  5],
       [ 7, 18],
       [20, 12]])

In [5]:
def doubles():
    print('*** Find rows wih same values in a matrix or 2D Numpy array***')
    # Check rows in which all values are equal
    number_of_doubles = 0
    for i in range(rolls.shape[0]):
        if np.all(rolls[i]==rolls[i][0]):
            number_of_doubles = number_of_doubles + 1
    return number_of_doubles
doubles()

*** Find rows wih same values in a matrix or 2D Numpy array***


516

In [6]:
chance_of_doubles = doubles()/rolls.shape[0]
chance_of_doubles
print(chance_of_doubles * 100, "% chance of rolling doubles")

*** Find rows wih same values in a matrix or 2D Numpy array***
5.16 % chance of rolling doubles


2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [37]:
n_trials = nrows = 100000
n_flips = ncols = 8
flips = np.random.choice([0, 1], n_trials * n_flips).reshape(nrows, ncols)
flips

array([[0, 1, 1, ..., 0, 1, 0],
       [0, 1, 1, ..., 1, 1, 0],
       [0, 0, 1, ..., 1, 1, 1],
       ...,
       [0, 0, 1, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 1, 0]])

In [38]:
def exactly_three_heads():
    # Check rows in which there are exactly 3 heads
    three_heads = 0
    for i in range(flips.shape[0]):
        if np.all(np.sum(flips[i]) == 3):
            three_heads = three_heads + 1
    return three_heads

exactly_three_heads()

22006

In [9]:
chance_of_exactly_3_heads = (exactly_three_heads()/flips.shape[0])
chance_of_exactly_3_heads
print(round((chance_of_exactly_3_heads * 100), 2), "% chance of getting exactly 3 heads")

21.75 % chance of getting exactly 3 heads


3.  There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [128]:
n_trials = nrows = 100
n_type = ncols = 2
drives = np.random.choice(2, n_trials * n_type, replace=True, p=[.75, .25]).reshape(nrows, ncols)
odds = drives.sum(axis=1)
odds = odds == 2
print(odds)
odds = odds.sum()
odds

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False  True False False False  True  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]


4

4.  Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [131]:
help(np.random.normal)

n_rows = 10_000
n_cols = 5 # to represent a 5 day week
mu = 3
sigma = 1.5
poptarts = np.random.normal(mu, sigma, size=(n_rows, n_cols)).round()
poptarts = pd.DataFrame(poptarts, columns=["Mon", "tues", "wed", "Thur", "Fri"])
poptarts.head()

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution

Mon  tues  wed  Thur  Fri
0  6.0   4.0  3.0   4.0  3.0
1  4.0   5.0  2.0   7.0  3.0
2  2.0   3.0  2.0   2.0  2.0
3  2.0   3.0  3.0   3.0  5.0
4  3.0   2.0  4.0   4.0  2.0

In [132]:
poptarts.min()

Mon    -3.0
tues   -3.0
wed    -3.0
Thur   -3.0
Fri    -3.0
dtype: float64

In [133]:
poptarts["n_consumed"] = poptarts.sum(axis=1)
poptarts.head()

Mon  tues  wed  Thur  Fri  n_consumed
0  6.0   4.0  3.0   4.0  3.0        20.0
1  4.0   5.0  2.0   7.0  3.0        21.0
2  2.0   3.0  2.0   2.0  2.0        11.0
3  2.0   3.0  3.0   3.0  5.0        16.0
4  3.0   2.0  4.0   4.0  2.0        15.0

In [134]:
# What's the chance we can buy poptarts on Friday afternoon
# This setpup would predicate
(poptarts.n_consumed < 17).mean()

0.6762

5. Compare Heights
- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [ ]:
m_heights = np.random.normal(178, 8, size=10_000)
f_heights = np.random.normal(178, 6, size=10_000)
(f_heights > )

6. a. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [135]:
n_rows = 100_000
n_columns = 50

installs = np.random.choice([0,1], p=[0.004, 0.996], size=(n_rows, n_columns))

(installs.sum(axis=1) == 50).mean()

0.81982

6. b. What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [ ]:
n_columns = 100
installs = np.random.choce

6. c. How likely is it that 450 students all download anaconda without an issue?

In [ ]:
n_columns = 450

7. a. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [ ]:
n_rows = 10_000
n_cols = 3 # to represent 3 days in a row

trucks = np.random.choice([1, 0], size=(n_rows, n_cols), p=[0.7, 0.3])

In [ ]:
trucks.um(axis=1) == 0_.mean()

7. b. How likely is it that a food truck will show up sometime this week?

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [ ]:
n_rows = 10_000
n_cols = 23 # to represent 23 individuals

birthdays = np.random.choice(range(365), size=(n_rows, n_sols))
birthdays = pd.DataFrame(birthdays)
birthdays["n_unique"] = birthdays.nunique(axis=1)

#
(birthdays.n_unique != 23.mean())

In [137]:
n_rows = 10_000
n_cols = 40 # to represent 40 individuals

birthdays = np.random.choice(range(365), size=(n_rows, n_sols))
birthdays = pd.DataFrame(birthdays)
birthdays["n_unique"] = birthdays.nunique(axis=1)

#What's the proportion of rows where we have multiple shared days
(birthdays.n_unique != 40).mean()

NameError: name 'n_sols' is not defined

In [ ]:
x = rang(1, 100)


N = [n* (n-1) / 2 for n in x]

y = [1 - (364/365)**n for n in N]

In [ ]:
import matplotlib.pyplot as plt

plt.title()

# Bonus Exercises

- [Mage Duel](https://gist.github.com/ryanorsinger/2996446f02c1bf30fcb3f8fdb88bd51d)

- [Chuck a Luck](https://gist.github.com/ryanorsinger/eac1d7b7e978f90b8390bdc056312123)